#define MyAppName "LaunchPad"
#define MyAppVersion "1.0.2"
#define MyAppPublisher "LaunchPad"
#define MyAppExeName "LaunchPad.exe"
#ifndef QemuRuntimeRoot
  #define QemuRuntimeRoot "..\dist"
#endif
#ifndef NativeOnly
  #ifndef RuntimeFilesInclude
    #error Full packages require the validated runtime include generated by scripts/publish.ps1.
  #endif
#endif

#ifdef NativeOnly
  #define ComplianceProfile "Native"
#else
  #define ComplianceProfile "Full"
#endif
#if Exec("powershell.exe", "-NoProfile -ExecutionPolicy Bypass -File " + AddQuotes(SourcePath + "..\scripts\verify-third-party.ps1") + " -Profile " + ComplianceProfile + " -DistributionRoot " + AddQuotes(SourcePath + "..\dist"), SourcePath, 1, SW_HIDE) != 0
  #error Third-party compliance preflight failed. Run scripts/verify-third-party.ps1 for the missing file or provenance details.
#endif

#ifndef NativeOnly
  #if Exec("py.exe", "-3 " + AddQuotes(SourcePath + "..\scripts\verify-release-image.py") + " --runtime-root " + AddQuotes(QemuRuntimeRoot), SourcePath, 1, SW_HIDE) != 0
    #error Release guest cleanup check failed. No Full installer may contain rejected guest or maintenance leftovers.
  #endif
#endif

[Setup]
AppId={{8F3A1C2E-6B47-4D19-9C5A-71E0B4D84A21}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={localappdata}\Programs\LaunchPad
UsePreviousAppDir=no
UninstallDisplayName={#MyAppName}
; Older installers recorded deletion of images that now back saved sessions.
; Start a new log lineage without discarding/editing those legacy logs. Full
; and Native continue sharing this location; retained images are not deleted.
UninstallFilesDir={app}\uninstall-state-v2
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
OutputDir=..\dist
#ifdef NativeOnly
OutputBaseFilename=LaunchPad-Native-Setup
#else
OutputBaseFilename=LaunchPad-Setup
#endif
SetupIconFile=LaunchPad.ico
UninstallDisplayIcon={app}\{#MyAppExeName}
Compression=lzma2
SolidCompression=no
#ifdef NativeOnly
DiskSpanning=no
#else
DiskSpanning=yes
DiskSliceSize=600000000
#endif
WizardStyle=modern
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableWelcomePage=no
InfoBeforeFile=..\DOWNLOAD-NOTE.txt
SetupLogging=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a Desktop shortcut"; GroupDescription: "Shortcuts:"; Flags: unchecked
Name: "startmenuicon"; Description: "Create a Start Menu shortcut"; GroupDescription: "Shortcuts:"; Flags: unchecked

[Dirs]
#ifndef NativeOnly
Name: "{app}\sessions"
Name: "{app}\qemu"
Name: "{app}\images"
#endif
[Files]
#ifndef NativeOnly
Source: "SetupPrepare.ps1"; Flags: dontcopy
#endif
Source: "..\dist\LaunchPad.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\README.md"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\DOWNLOAD-NOTE.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\LICENSE"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\NOTICE"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\dist\THIRD-PARTY-NOTICES.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\dist\licenses\*"; DestDir: "{app}\licenses"; Flags: ignoreversion recursesubdirs createallsubdirs
#ifdef NativeOnly
Source: "native-only.txt"; DestDir: "{app}"; Flags: ignoreversion
#else
; Prepared guest and QEMU. No grok.exe, no libguestfs, no WSL, and no password file.
; SetupPrepare.ps1 enables HypervisorPlatform when that feature is off.
; It calls New-LocalUser for BuildLaunchTest only when that account is missing.
; Only the Fence machine emulator, its DLLs, required image utility and firmware.
Source: "{#QemuRuntimeRoot}\qemu\fence\qemu-system-x86_64.exe"; DestDir: "{app}\qemu\fence"; Flags: ignoreversion
Source: "{#QemuRuntimeRoot}\qemu\fence\*.dll"; DestDir: "{app}\qemu\fence"; Flags: ignoreversion
Source: "{#QemuRuntimeRoot}\qemu\qemu-img.exe"; DestDir: "{app}\qemu"; Flags: ignoreversion
Source: "{#QemuRuntimeRoot}\qemu\*.dll"; DestDir: "{app}\qemu"; Flags: ignoreversion
; This Fence build disables GTK/SDL and needs no vendor desktop or translation assets.
Source: "{#QemuRuntimeRoot}\qemu\share\*"; DestDir: "{app}\qemu\share"; Excludes: "applications\*,doc\*,icons\*,locale\*,man\*"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#QemuRuntimeRoot}\qemu\fence\COPYING"; DestDir: "{app}\qemu\fence"; Flags: ignoreversion
#include RuntimeFilesInclude
Source: "{#QemuRuntimeRoot}\qemu\fence\QEMU-SOURCE.txt"; DestDir: "{app}\qemu\fence"; Flags: ignoreversion
#endif

[Icons]
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: startmenuicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "Start LaunchPad"; Flags: nowait postinstall skipifsilent unchecked

; User settings, credentials, project records and session disks survive uninstall.

[Code]
#ifndef NativeOnly
function NextButtonClick(CurPageID: Integer): Boolean;
var
  ResultCode: Integer;
begin
  Result := True;
  if CurPageID <> wpReady then
    exit;

  ExtractTemporaryFile('SetupPrepare.ps1');
  if (not Exec(ExpandConstant('{sys}\WindowsPowerShell\v1.0\powershell.exe'),
    '-NoProfile -ExecutionPolicy Bypass -File "' + ExpandConstant('{tmp}\SetupPrepare.ps1') + '"',
    '', SW_HIDE, ewWaitUntilTerminated, ResultCode)) or (ResultCode <> 0) then
  begin
    MsgBox('Setup stopped before it copied files.', mbError, MB_OK);
    Result := False;
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode: Integer;
  FenceShare, QemuShare: String;
begin
  if CurStep <> ssPostInstall then
    exit;

  // The console-size QEMU runs from qemu\fence with its own DLLs.
  // Its working directory is that folder, and -L share reads firmware there.
  // The junction points at the firmware already installed in qemu\share.
  FenceShare := ExpandConstant('{app}\qemu\fence\share');
  QemuShare := ExpandConstant('{app}\qemu\share');
  if (not DirExists(FenceShare)) and DirExists(QemuShare) and DirExists(ExpandConstant('{app}\qemu\fence')) then
    Exec(ExpandConstant('{cmd}'),
      '/c mklink /J "' + FenceShare + '" "' + QemuShare + '"',
      '', SW_HIDE, ewWaitUntilTerminated, ResultCode);

  ForceDirectories(ExpandConstant('{app}\sessions'));
  // The helper selects executable/deps/QEMU/image inputs. It never recursively
  // grants the app or session root, overwrites disks, or falls back to dev QEMU.
  if (not Exec(ExpandConstant('{app}\{#MyAppExeName}'),
    '--activate-runtime "{#RuntimeManifestInstallName}"', '', SW_HIDE, ewWaitUntilTerminated, ResultCode)) or (ResultCode <> 0) then
    RaiseException('Files were copied, but the new runtime could not be verified or activated. The previous runtime selection and existing disks were preserved. Open LaunchPad Settings -> Repair setup; conflicting image files or missing credentials need attention.');

  // Retain native mode through a failed full-package activation.
  if FileExists(ExpandConstant('{app}\native-only.txt')) and (not DeleteFile(ExpandConstant('{app}\native-only.txt'))) then
    RaiseException('Runtime verified, but the native package marker could not be removed. Close LaunchPad and run setup again.');

end;
#endif
